spring.datasource.url=jdbc:postgresql://3.136.16.248:5432/raissabd?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=postgres13

# esta ruta apunta al gesconnect
conector.api.url=http://localhost:8092
raissa.sistema.codigo=002

raissa.seguridad.dias.expiracion.clave=90

# ============================================
# RABBITMQ - PROD
# ============================================
spring.rabbitmq.host=3.136.16.248
spring.rabbitmq.port=5672
spring.rabbitmq.username=raissa
spring.rabbitmq.password=S3cr3t0
spring.rabbitmq.virtual-host=prod

# Timeouts
spring.rabbitmq.connection-timeout=30000
spring.rabbitmq.requested-heartbeat=60

# Nombre de colas
payments.queue.consulta.name=payments.consulta.transferencia
payments.queue.confirmacion.name=payments.aplicacion.transferencia

# ============================================
# SERVIDOR DE AUTORIZACION
# ============================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://3.136.16.248:9000

# ============================================
# LOGGING PROD
# ============================================
logging.level.com.raissa.payments=INFO