# ============================================
# BASE DE DATOS
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:3308/raissabd?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=123

# esta ruta apunta al gesconnect
conector.api.url=http://localhost:8092
raissa.sistema.codigo=002

# Hosts permitidos ante control CORS
raissa.seguridad.dias.expiracion.clave=90

# ============================================
# RABBITMQ - DEV
# ============================================
spring.rabbitmq.host=100.122.165.121
spring.rabbitmq.port=5672
spring.rabbitmq.username=raissa
spring.rabbitmq.password=S3cr3t0
spring.rabbitmq.virtual-host=dev

# Nombre de colas
payments.queue.consulta.name=payments.consulta.transferencia
payments.queue.confirmacion.name=payments.aplicacion.transferencia

# Timeouts
spring.rabbitmq.connection-timeout=30000
spring.rabbitmq.requested-heartbeat=60

# ============================================
# SERVIDOR DE AUTORIZACION
# ============================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

# ============================================
# LOGGING DEV
# ============================================
logging.level.com.raissa.payments=DEBUG
logging.level.org.springframework.amqp=DEBUG