server.port=8091

spring.datasource.url=jdbc:postgresql://3.136.16.248:5432/raissabd?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=postgres13

logging.level.com.raissa.payments: DEBUG

# esta ruta apunta al gesconnect
conector.api.url=http://localhost:8092
raissa.sistema.codigo=002

raissa.seguridad.dias.expiracion.clave=90

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://3.136.16.248:9000